# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  migrate:
    cmds:
      - migrate -path db/migrations -database "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}" {{.cmd}}
  create-migration:
    cmds:
      - migrate create -ext sql -dir db/migrations/ -seq {{.name}}
  dev:
    cmds:
      - go run ./main.go
  lint-fix:
    cmds:
      - gofmt -w .
  lint-ci:
    cmds:
      - golangci-lint run
